name: Bug Report
description: Create a report to help us improve SolaceAudio
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please fill out the sections below as accurately as possible.
  - type: input
    id: lavalink_version
    attributes:
      label: Lavalink Version
      description: What version of Lavalink are you running? (e.g., 4.0.8)
      placeholder: "4.0.8"
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: SolaceAudio Version
      description: What version/commit of SolaceAudio are you using?
      placeholder: "v1.0.0"
    validations:
      required: true
  - type: textarea
    id: problem_description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Stacktrace
      description: Paste relevant Lavalink terminal logs here (surround with ```).
      render: shell
    validations:
      required: false
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      placeholder: |
        1. Search track using 'spsearch:...'
        2. Attempt playback on voice channel
        3. See error in logs
    validations:
      required: false
