name: Feature Request
description: Suggest an idea or enhancement for SolaceAudio
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make SolaceAudio faster or support new sources? Let us know!
  - type: textarea
    id: feature_summary
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature or enhancement you would like to see.
    validations:
      required: true
  - type: textarea
    id: problem_or_use_case
    attributes:
      label: Problem / Use Case
      description: Is your feature request related to a specific problem or workflow?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you have considered.
    validations:
      required: false
